name: pypi-publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - 'pyproject.toml'
  workflow_dispatch:
    inputs:
      dry_run:
        type: choice
        description: Dry run mode
        required: true
        options:
          - "true"
          - "false"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pypi-publisher:
    runs-on: thevickypedia-lite
    steps:
      - name: Set dry-run
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::notice title=DryRun::Setting dry run to ${{ inputs.dry_run }} for '${{ github.event_name }}' event"
            echo "dry_run=${{ inputs.dry_run }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "::notice title=DryRun::Setting dry run to true for '${{ github.event_name }}' event"
            echo "dry_run=true" >> $GITHUB_ENV
          else
            echo "::notice title=DryRun::Setting dry run to false for '${{ github.event_name }}' event"
            echo "dry_run=false" >> $GITHUB_ENV
          fi
        shell: bash
      - uses: thevickypedia/pypi-publisher@v4
        env:
          token: ${{ secrets.PYPI_TOKEN }}
        with:
          dry-run: ${{ env.dry_run }}
